# Generated by Django 3.1.6 on 2021-02-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_remove_usuario_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(default='', max_length=100, verbose_name='Sobrenome'),
        ),
    ]
